// Package manager exposes mocks for the manager package
package manager

import mock "github.com/stretchr/testify/mock"
import task "github.com/wayofthepie/task-executor/pkg/model/task"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ManageExecutingTask provides a mock function with given fields: taskInfo, quit
func (_m *Service) ManageExecutingTask(taskInfo task.Info, quit chan int) (*task.Info, error) {
	ret := _m.Called(taskInfo, quit)

	var r0 *task.Info
	if rf, ok := ret.Get(0).(func(task.Info, chan int) *task.Info); ok {
		r0 = rf(taskInfo, quit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Info)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(task.Info, chan int) error); ok {
		r1 = rf(taskInfo, quit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
